# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0002_remove_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(help_text='GM-only notes'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.TextField(help_text='GM-only notes'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='on_success',
            field=models.ForeignKey(blank=True, help_text='The mission to trigger on success', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_on_success', to='gm.Stage'),
        ),
    ]
