# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0003_auto_20170129_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
