# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0004_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='on_success',
            field=models.ForeignKey(blank=True, help_text='The stage to trigger on success', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_on_success', to='gm.Stage'),
        ),
    ]
