# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0005_auto_20170206_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='code',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='uid',
        ),
    ]
