# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0006_auto_20170211_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='claimed',
            field=models.BooleanField(default=False, help_text='Has this mission been started by a team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='codeword',
            field=models.CharField(help_text='Secret code required for some missions', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='minutes_to_run',
            field=models.IntegerField(default=30, help_text='How long should the mission be available?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
