# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0007_auto_20170211_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='start_stage',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
