# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0008_stage_start_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='contact',
        ),
        migrations.AddField(
            model_name='mission',
            name='contact',
            field=models.ManyToManyField(to='gm.Contact'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='codeword',
            field=models.CharField(blank=True, help_text='Secret code required for some missions', max_length=255, null=True),
        ),
    ]
