# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0009_auto_20170212_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='current_characters',
        ),
    ]
