# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0010_remove_stage_current_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='skills_needed',
            field=models.ManyToManyField(related_name='skills_needed', to='gm.Skill'),
        ),
    ]
