# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0011_auto_20170212_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='registered',
            field=models.BooleanField(default=False, help_text='Is the super government registered'),
            preserve_default=False,
        ),
    ]
