# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0013_stage_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='skills',
        ),
    ]
