# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0015_auto_20170225_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterskilllink',
            name='character',
        ),
        migrations.RemoveField(
            model_name='characterskilllink',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='character',
            name='skills',
        ),
        migrations.DeleteModel(
            name='CharacterSkillLink',
        ),
    ]
