# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0016_auto_20170225_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSkillLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.Character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gm.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(through='gm.CharacterSkillLink', to='gm.Skill'),
        ),
    ]
