# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0017_auto_20170225_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='news_message',
            field=models.TextField(default='Trouble at the gasworks', help_text='Mission info displayed in news feeds'),
            preserve_default=False,
        ),
    ]
