# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0018_mission_news_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='on_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_on_failure', to='gm.Mission'),
        ),
        migrations.AddField(
            model_name='mission',
            name='on_failure_delay',
            field=models.IntegerField(blank=True, help_text='How long should mission on success be delayed', null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='on_success',
            field=models.ForeignKey(blank=True, help_text='The stage to trigger on success', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_on_success', to='gm.Mission'),
        ),
        migrations.AddField(
            model_name='mission',
            name='on_success_delay',
            field=models.IntegerField(blank=True, help_text='How long should mission on success be delayed', null=True),
        ),
    ]
