# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0020_auto_20170226_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='on_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_on_failure', to='gm.Mission'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='on_success',
            field=models.ForeignKey(blank=True, help_text='The mission to trigger on success', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_on_success', to='gm.Mission'),
        ),
    ]
