# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0021_auto_20170226_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='contact',
            field=models.ManyToManyField(blank=True, null=True, to='gm.Contact'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True, help_text='GM-only notes', null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='news_on_failure',
            field=models.ManyToManyField(blank=True, null=True, related_name='news_on_failure', to='gm.News'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='news_on_success',
            field=models.ManyToManyField(blank=True, null=True, related_name='news_on_success', to='gm.News'),
        ),
    ]
