# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0022_auto_20170226_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='cooldown_on_failure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='cooldown_on_success',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
