# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0023_auto_20170226_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='repetitions',
            field=models.IntegerField(default=1, help_text='How many times can the mission be re-run. (To use this, the mission should trigger itself on success and/or failure)'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='contact',
            field=models.ManyToManyField(blank=True, to='gm.Contact'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='news_on_failure',
            field=models.ManyToManyField(blank=True, related_name='news_on_failure', to='gm.News'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='news_on_success',
            field=models.ManyToManyField(blank=True, related_name='news_on_success', to='gm.News'),
        ),
    ]
