# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0024_auto_20170226_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='fail_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='success_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
