# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0025_auto_20170226_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
