# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0026_remove_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='team_members', to='gm.Character'),
        ),
    ]
