# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0029_auto_20170302_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='member_of',
            field=models.ManyToManyField(through='gm.TeamCharacterLink', to='gm.Team'),
        ),
    ]
