# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0031_news_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='cooldown',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
