# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0034_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='bonus',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
