# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0035_stage_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='news_message',
        ),
        migrations.AddField(
            model_name='mission',
            name='news_on_trigger',
            field=models.ManyToManyField(blank=True, help_text='Secret code required for some missions', related_name='news_on_trigger', to='gm.News'),
        ),
    ]
