# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0036_auto_20170304_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='contact',
        ),
    ]
