# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0038_mission_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='minutes_to_run',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='on_failure',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='on_failure_delay',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='on_success',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='on_success_delay',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='start_time',
        ),
    ]
