# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0039_auto_20170322_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck to stop news being shown'),
        ),
    ]
