# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0042_character_gm_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='deactivated',
            field=models.BooleanField(default=True, help_text='Is this character in the game'),
            preserve_default=False,
        ),
    ]
