# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0043_character_deactivated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='deactivated',
            new_name='active',
        ),
    ]
